/**
 * generate-imports command - Generate plugin import mappings
 */

import { writeFileSync, existsSync, mkdirSync, readdirSync, readFileSync } from 'fs'
import { resolve, dirname, join, relative } from 'path'
import { loadConfig } from '../utils/config-loader'

interface PluginInfo {
  id: string
  path: string // Relative path from pluginsDir to plugin directory
  manifest: any
}

function discoverPlugins(pluginsDir: string): PluginInfo[] {
  console.log('[INFO] Discovering plugins...')
  
  if (!existsSync(pluginsDir)) {
    console.log('[WARN] Plugin directory does not exist:', pluginsDir)
    return []
  }
  
  const validPlugins: PluginInfo[] = []
  
  // Recursively scan for plugins
  function scanDirectory(dir: string, relativePath: string = ''): void {
    const entries = readdirSync(dir, { withFileTypes: true })
    
    for (const entry of entries) {
      if (!entry.isDirectory()) {
        continue
      }
      
      const fullPath = join(dir, entry.name)
      const currentRelativePath = relativePath ? `${relativePath}/${entry.name}` : entry.name
      const manifestPath = join(fullPath, 'manifest.json')
      
      // Check if this directory contains a manifest.json (it's a plugin)
    if (existsSync(manifestPath)) {
      try {
        const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
          // Use the plugin ID from manifest, or fallback to directory name
          const pluginId = manifest.id || entry.name
          
        if (manifest.enabled !== false) {
          validPlugins.push({
              id: pluginId,
              path: currentRelativePath,
            manifest: manifest
          })
            console.log(`[OK] Found plugin: ${pluginId} (${currentRelativePath})`)
        } else {
            console.log(`[SKIP] Plugin disabled: ${pluginId}`)
          }
        } catch (error: any) {
          console.warn(`[WARN] Plugin ${currentRelativePath} manifest file is invalid:`, error.message)
        }
      } else {
        // Recursively scan subdirectories
        scanDirectory(fullPath, currentRelativePath)
      }
    }
  }
  
  scanDirectory(pluginsDir)
  
  return validPlugins
}

function generateImportMappings(plugins: PluginInfo[], pluginsDir: string, outputFile: string): string {
  const imports: string[] = []
  const mappings: string[] = []
  const manifests: string[] = []
  const outputDir = dirname(outputFile)
  
  // Generate import statements and manifest info
  plugins.forEach(plugin => {
    // Remove file extension, let TypeScript handle it
    const entryPath = plugin.manifest.entry.replace(/^\.\//, '').replace(/\.(tsx|ts|js|mjs)$/, '')
    // Calculate relative path from output file to plugin entry file
    // Use plugin.path instead of plugin.id to handle nested directories
    const pluginEntryFile = resolve(pluginsDir, plugin.path, entryPath)
    const relativePath = relative(outputDir, pluginEntryFile)
    // Ensure path uses forward slashes and doesn't start with ./
    const importPath = relativePath.replace(/\\/g, '/').replace(/^\.\//, '')
    
    // Convert plugin ID to valid JavaScript variable name
    const validVariableName = plugin.id.replace(/[^a-zA-Z0-9_]/g, '_')
    const importName = `${validVariableName}PluginImport`
    
    imports.push(`import ${importName} from '${importPath}';`)
    mappings.push(`  '${plugin.id}': () => ${importName},`)
    
    // Add manifest info
    manifests.push(`  '${plugin.id}': ${JSON.stringify(plugin.manifest, null, 2)},`)
  })
  
  // Generate complete TypeScript file
  const content = `// Auto-generated plugin import mapping file
// This file is generated by slotkit generate-imports at build time
// Do not modify this file manually

${imports.join('\n')}

/**
 * Plugin import mapping
 * Key: plugin ID, Value: plugin module import function
 */
export const pluginImports = {
${mappings.join('\n')}
};

/**
 * Plugin manifest mapping
 * Key: plugin ID, Value: plugin manifest
 */
export const pluginManifests = {
${manifests.join('\n')}
};

/**
 * Get plugin import function
 */
export function getPluginImport(pluginId: string) {
  return pluginImports[pluginId as keyof typeof pluginImports];
}

/**
 * Get plugin manifest
 */
export function getPluginManifest(pluginId: string) {
  return pluginManifests[pluginId as keyof typeof pluginManifests];
}

/**
 * Get all available plugin IDs
 */
export function getAvailablePluginIds(): string[] {
  return Object.keys(pluginImports);
}

/**
 * Get all plugin manifests
 */
export function getAllPluginManifests() {
  return Object.values(pluginManifests);
}

// Generated at: ${new Date().toISOString()}
// Plugin count: ${plugins.length}
`

  return content
}

export async function generateImports(): Promise<void> {
  console.log('[INFO] Plugin import mapper starting')
  
  const config = loadConfig()
  const pluginsDir = resolve(process.cwd(), config.pluginsDir || './plugins')
  const outputFile = resolve(process.cwd(), config.outputDir || './src/core/plugin/loader/plugin-imports.generated.ts')
  
  const plugins = discoverPlugins(pluginsDir)
  
  if (plugins.length === 0) {
    console.log('[WARN] No plugins found')
    // Even if there are no plugins, generate an empty import mapping file
    const emptyContent = `// Auto-generated plugin import mapping file
// This file is generated by slotkit generate-imports at build time
// Do not modify this file manually

/**
 * Plugin import mapping
 * Key: plugin ID, Value: plugin module import function
 */
export const pluginImports = {};

/**
 * Plugin manifest mapping
 * Key: plugin ID, Value: plugin manifest
 */
export const pluginManifests = {};

/**
 * Get plugin import function
 */
export function getPluginImport(pluginId: string) {
  return pluginImports[pluginId as keyof typeof pluginImports];
}

/**
 * Get plugin manifest
 */
export function getPluginManifest(pluginId: string) {
  return pluginManifests[pluginId as keyof typeof pluginManifests];
}

/**
 * Get all available plugin IDs
 */
export function getAvailablePluginIds(): string[] {
  return Object.keys(pluginImports);
}

/**
 * Get all plugin manifests
 */
export function getAllPluginManifests() {
  return Object.values(pluginManifests);
}

// Generated at: ${new Date().toISOString()}
// Plugin count: 0
`
    
    const outputDir = dirname(outputFile)
    if (!existsSync(outputDir)) {
      mkdirSync(outputDir, { recursive: true })
    }
    writeFileSync(outputFile, emptyContent, 'utf8')
    console.log(`[OK] Empty import mapping generated: ${outputFile}`)
    return
  }
  
  // Generate import mappings with correct relative paths
  const content = generateImportMappings(plugins, pluginsDir, outputFile)
  
  // Ensure output directory exists
  const outputDir = dirname(outputFile)
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true })
  }
  
  // Write file
  writeFileSync(outputFile, content, 'utf8')
  
  console.log(`[OK] Plugin import mapping generated: ${outputFile}`)
  console.log(`[INFO] Processed ${plugins.length} plugin(s)`)
  
  // Display generated plugin list
  plugins.forEach(plugin => {
    console.log(`  • ${plugin.manifest.name} (${plugin.id})`)
  })
}

